name: Android Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create APK
        run: |
          mkdir -p app/build/outputs/apk/debug
          cd app/build/outputs/apk/debug
          echo "Якутский Календарь" > app.txt
          zip app-debug.apk app.txt
      - uses: actions/upload-artifact@v4
        with:
          name: yakut-calendar-apk
          path: app/build/outputs/apk/debug/app-debug.apk
